### Get tasks
GET https://todo-backend-3zqj.onrender.com

### Add new task
POST https://todo-backend-3zqj.onrender.com/new HTTP/1.1
Content-Type: application/json

{
    "description": "Test from REST Client"
}

// part5_Test created endpoint with Rest Client by creating the following script. HTTP method is delete and the id (in this example 1) for the deleted record (task) on the database is part of url (HTTP query parameter)

### Delete task
DELETE https://todo-backend-3zqj.onrender.com/delete/37 HTTP/1.1